services:
  vpn-server:
    build:
      context: .
      dockerfile: vpn-server/Dockerfile
    image: vpn-server:latest
    volumes:
      - ./config/server.yml:/etc/vpn/config.yml
    networks:
      vpn_net:
        ipv4_address: 10.0.0.20

  vpn-client:
    build:
      context: .
      dockerfile: vpn-client/Dockerfile
    image: vpn-client:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config/client.yml:/etc/vpn/config.yml
    networks:
      vpn_net:
        ipv4_address: 10.0.0.10
    depends_on:
      - vpn-server

networks:
  vpn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16
