# Настройки сервера
listen-address: '0.0.0.0' # Адрес для прослушивания
listen-port: 9696 # Порт для прослушивания

# Ограничения клиентов
max-clients: 10 # Максимальное количество одновременных подключений
client-timeout-secs: 30 # Таймаут неактивности клиента в секундах

# Разрешенные клиенты
client-credentials:
  - type: 'password'
    username: 'user1'
    password: 'pass1'
  - type: 'password'
    username: 'user2'
    password: 'pass2'
