server-address: '172.20.0.2'
server-port: 8000
listen-address: '0.0.0.0'
listen-port: 6969
reconnect-interval-secs: 5
connect-timeout-secs: 10
credentials:
  type: 'password'
  username: 'test_user'
  password: 'test_pass'
tun:
  name: 'tun0'
  address: '10.0.0.2'
  netmask: '255.255.255.0'
  mtu: 1500
  up: true 
