# Настройки подключения к серверу
server-address: '0.0.0.0' # IP-адрес VPN сервера
server-port: 9696 # Порт VPN сервера

# Локальные настройки
listen-address: '0.0.0.0' # Адрес для прослушивания
listen-port: 6969 # Локальный порт

# Таймауты и интервалы
reconnect-interval-secs: 5 # Интервал переподключения в секундах
connect-timeout-secs: 10 # Таймаут подключения в секундах

# Учетные данные
credentials:
  type: 'password'
  username: 'user1' # Имя пользователя
  password: 'pass1' # Пароль

# Настройки TUN интерфейса
tun:
  name: 'utun10' # Имя интерфейса
  address: '10.0.1.10' # IP-адрес интерфейса
  netmask: '255.255.255.0' # Маска подсети
  mtu: 1500 # MTU
  up: true # Поднимать интерфейс автоматически
