[package]
name = "vpn-shared"
version = "0.0.0"
edition = "2021"

[lib]

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
chacha20poly1305 = "0.10.1"
rand = "0.8.5"
