[package]
name = "vpn-shared"
version = "0.0.0"
edition = "2021"

[lib]

[dependencies]
anyhow = { workspace = true }
xxhash-rust = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
